name: Build Desktop App (Ubuntu)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libglib2.0-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libpng-dev \
            libjpeg-dev \
            libtiff-dev \
            libexpat1-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            freeglut3-dev \
            build-essential \
            pkg-config

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable (Linux)
        run: |
          pyinstaller --onefile main.py \
            --add-data "assets/*:assets" \
            --icon=assets/brain.ico

      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build
          path: dist/*
          if-no-files-found: error
