name: Build with PyInstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --name dcm2bids --onefile --windowed \
            --icon=assets/brain.ico \
            --add-data "assets:assets" \
            --add-data "dcm2bids.json:." \
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dcm2bids-${{ matrix.os }}
          path: dist/*
