name: Build with PyInstaller (Windows, Python 3.12)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Confirm Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --name dcm2bids --onefile --windowed ^
            --icon=assets/brain.ico ^
            --add-data "assets;assets" ^
            --add-data "dcm2bids.json;." ^
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dcm2bids-windows-py312
          path: dist/*
